# @package _global_

train_base: False
alg: cl
lr: 1e-5
edit_lr: 1e-4
lr_lr: 1e-4
cl:
  verbose: false
  max_edit_steps: 100
  time_limit: null
  locality:
    enabled: false
    oracle: true
    cedit: 1e-2
    batch_size: 1
  rank: null
  init_std: 0.01
